services:
  - type: web
    name: pid-scanner-ocr
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /_stcore/health
    envVars:
      - key: PORT
        value: 8501
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0